import Archerpushups from '../../Assets/ExerciseGif/ArcherPushups.gif';
import assistedpullups from '../../Assets/ExerciseGif/assistedpullups.gif';
import benchpress from '../../Assets/ExerciseGif/benchpress.gif';
import pulldowns from '../../Assets/ExerciseGif/pulldowns.gif';
import quadstrech from '../../Assets/ExerciseGif/quadstrech.gif';
import situps from '../../Assets/ExerciseGif/situps.gif';
import burpee from '../../Assets/ExerciseGif/burpee.gif';
import bicepcurls from '../../Assets/ExerciseGif/bicepcurls.gif';
import astridejumps from '../../Assets/ExerciseGif/astridejumps.gif';


const exer = [
  { id: 'Archerpushups', src: Archerpushups, alt: 'Archer Pushups', text: 'Archer Pushups', description: 'Archer push-ups, also known as side-to-side push-ups, are an advanced push-up variation. To practice archer push-ups, start in a push-up position with your hands placed wider than shoulder-width apart. Keeping your body in a straight line, bend one elbow while keeping the opposite arm straight. Your straight arm will offer some support while your other arm holds your bodyweight. Archer push-ups place greater intensity on your back and arm muscles, making them great bodyweight exercises to incorporate in gymnastics and bodybuilding routines.', link: '/exercises/Archerpushups', bodypart: 'Chest', target: 'Pectoral', equipment: 'Bodyweight' },

  { id: 'Assistedpullups', src: assistedpullups, alt: 'Assisted Pullups', text: 'Assisted Pullups', description: 'Assisted pull-ups use a machine or resistance bands to reduce the weight lifted during the exercise, allowing individuals to perform the movement with proper form and gradually build strength. This modification is ideal for beginners or those working to improve their upper body and back muscles.', link: '/exercises/Assistedpullups', bodypart: 'Back', target: 'Lats', equipment: 'Pullup machine' },

  { id: 'Benchpress', src: benchpress, alt: 'Barbell Benchpress', text: 'Barbell Benchpress', description: 'The barbell bench press is a fundamental strength training exercise targeting the chest, shoulders, and triceps. Performed while lying on a bench, the lifter lowers a weighted barbell to their chest and then presses it upwards until their arms are fully extended. This compound movement is essential for building upper body strength and muscle mass. It engages the pectoral muscles primarily, while also working the deltoids, triceps, and stabilizing muscles. Proper form and control are crucial to avoid injury and maximize effectiveness. The barbell bench press can be adapted with variations like incline, decline, or different grips to target specific muscle groups.', link: '/exercises/Benchpress', bodypart: 'Chest', target: 'Pectoral', equipment: 'Barbell' },

  { id: 'Pulldown', src: pulldowns, alt: 'Cable Pulldowns', text: 'Cable Pulldowns', description: 'Lat pulldowns are a popular strength training exercise that primarily targets the latissimus dorsi muscles in the back. Performed on a cable machine, the exercise involves pulling a bar down towards the chest from an overhead position while seated, with arms extended and knees secured under pads. This movement mimics a pull-up but allows for adjustable resistance, making it accessible for all fitness levels. Lat pulldowns also engage the biceps, shoulders, and upper back, promoting overall upper body strength and muscle development. Proper form, including controlled movements and avoiding excessive swinging, is essential to maximize benefits and prevent injury..', link: '/exercises/Pulldown', bodypart: 'Back', target: 'Lats', equipment: 'Pulldown machine' },

  { id: 'Quadstrech', src: quadstrech, alt: 'Quad Stretch', text: 'Quad Stretch', description: 'The kneeling quad stretch is a flexibility exercise that targets the quadriceps muscles located at the front of the thighs. To perform it, kneel on one knee with the other foot planted in front, creating a 90-degree angle at both knees. Gently push the hips forward while grasping the ankle or foot of the rear leg, pulling it towards the glutes. This stretch helps to improve flexibility, reduce muscle tightness, and alleviate discomfort in the quadriceps. Its particularly beneficial for athletes and individuals with tight or overworked quads. Maintaining a straight posture and avoiding excessive force is crucial for an effective and safe stretch.', link: '/exercises/QuadStretch', bodypart: 'Legs', target: 'Quads', equipment: 'Bodyweight' },

  { id: 'Situps', src: situps, alt: 'Half Situps', text: 'Half Situps', description: 'Half sit-ups, also known as crunches, are a core exercise that targets the abdominal muscles. Unlike full sit-ups, where the torso is lifted completely off the ground, half sit-ups involve raising the upper back and shoulders off the floor while keeping the lower back in contact with the ground. This movement isolates the rectus abdominis and helps build core strength and endurance. To perform half sit-ups, lie on your back with knees bent and feet flat on the floor, cross your arms over your chest, and lift your upper body slightly while engaging your abs. This exercise is effective for beginners and those looking to enhance their core stability.', link: '/exercises/Situps', bodypart: 'Chest', target: 'Pectoral', equipment: 'Bodyweight' },

  { id: 'Bicepcurls', src: bicepcurls, alt: 'Bicep Curls', text: 'Bicep Curls', description: 'xBicep curls are a fundamental strength training exercise targeting the biceps brachii muscles in the upper arms. They are typically performed using dumbbells, a barbell, or resistance bands. To execute a bicep curl, stand with feet shoulder-width apart, hold the weights with an underhand grip, and keep your elbows close to your torso. Curl the weights upward by flexing the elbows, bringing the weights towards your shoulders, and then slowly lower them back to the starting position. This exercise is essential for building arm strength and muscle definition. Proper form, including controlled movements and avoiding swinging, is crucial for maximizing effectiveness and preventing injury.', link: '/exercises/Bicepcurls', bodypart: 'Arms', target: 'Biceps', equipment: 'Resistance band' },

  { id: 'Burpees', src: burpee, alt: 'Burpees', text: 'Burpees', description: 'Burpees are a full-body, high-intensity exercise that combines strength training and cardiovascular conditioning. They begin in a standing position, then involve dropping into a squat, kicking the legs back into a plank position, performing a push-up, returning to the squat position, and finally jumping explosively into the air with arms extended overhead. Burpees engage multiple muscle groups including the chest, shoulders, arms, quads, hamstrings, and core, making them an efficient workout for strength, endurance, and calorie burning. They are popular in HIIT (High-Intensity Interval Training) routines due to their effectiveness in improving overall fitness levels. Proper form and pacing are important to avoid injury and maximize benefits.', link: '/exercises/Burpees', bodypart: 'Full Body', target: 'FullBody', equipment: 'Bodyweight' },

  { id: 'Astridejumps', src: astridejumps, alt: 'astridejumps', text: 'Astride Jumps', description: 'Astride jumps, also known as straddle jumps, are a plyometric exercise that targets the lower body muscles, particularly the quadriceps, hamstrings, and glutes. To perform astride jumps, start in a standing position with feet together. Then, jump explosively into the air while simultaneously spreading the legs apart laterally, landing with feet wider than hip-width apart. Next, jump back into the starting position, bringing the feet back together. Repeat the movement in a continuous, fluid motion. Astride jumps improve lower body power, agility, and coordination, making them beneficial for athletes and individuals aiming to enhance athletic performance or overall fitness levels. Its important to maintain proper landing mechanics and perform the exercise on a suitable surface to reduce impact on the joints.', link: '/exercises/Astridejumps', bodypart: 'Full Body', target: 'Full Body', equipment: 'Bodyweight' }
];

  export default exer;